var searchData=
[
  ['refresh',['refresh',['../classFedoraDatastream.html#a804b5ea979be5c43b5d5295bd9a20b7c',1,'FedoraDatastream\refresh()'],['../classFedoraObject.html#abe3a59a666de9f1a4318adc1ef92ecf5',1,'FedoraObject\refresh()']]],
  ['registernamespace',['registerNamespace',['../classFedoraRelationships.html#acef72f7d9b2cb1d36ec20eae861b444b',1,'FedoraRelationships']]],
  ['remove',['remove',['../classFedoraRelsExt.html#a06a61da3ba3ec3a1097cfcf8ef70a463',1,'FedoraRelsExt\remove()'],['../classFedoraRelsInt.html#a33ef6f1542818ffcb66c0086b6a36652',1,'FedoraRelsInt\remove()']]],
  ['repository_2ephp',['Repository.php',['../Repository_8php.html',1,'']]],
  ['repositorybadarguementexception',['RepositoryBadArguementException',['../classRepositoryBadArguementException.html',1,'']]],
  ['repositoryconfiginterface',['RepositoryConfigInterface',['../interfaceRepositoryConfigInterface.html',1,'']]],
  ['repositoryconnection',['RepositoryConnection',['../classRepositoryConnection.html',1,'']]],
  ['repositoryconnection_2ephp',['RepositoryConnection.php',['../RepositoryConnection_8php.html',1,'']]],
  ['repositoryexception',['RepositoryException',['../classRepositoryException.html',1,'']]],
  ['repositoryexception_2ephp',['RepositoryException.php',['../RepositoryException_8php.html',1,'']]],
  ['repositoryquery',['RepositoryQuery',['../classRepositoryQuery.html',1,'']]],
  ['repositoryquery_2ephp',['RepositoryQuery.php',['../RepositoryQuery_8php.html',1,'']]],
  ['repositoryrelationshipsexception',['RepositoryRelationshipsException',['../classRepositoryRelationshipsException.html',1,'']]],
  ['repositoryxmlerror',['RepositoryXmlError',['../classRepositoryXmlError.html',1,'']]],
  ['resetcache',['resetCache',['../classSimpleCache.html#a22e9a7af3a2efd58f9d2a7422a1b37cc',1,'SimpleCache']]],
  ['resumefindobjects',['resumeFindObjects',['../classFedoraApiA.html#accde22442ac4a85842a7b672bc34f207',1,'FedoraApiA\resumeFindObjects()'],['../classFedoraApiSerializer.html#a10332cadbe1e4410ab084b6fbdd99bdd',1,'FedoraApiSerializer\resumeFindObjects()']]]
];
